### ISSUE TITLE
Text widget font / size / window size

### ISSUE THREAD

**Issue by rjcahoy** [Rise-Vision/widget-text#100]
While editing text even after highlighting and changing the font and/or size it doesn't always update, and in some cases even after you save it will revert back.

I most commonly notice it on the first word of the entry - see below.  This was editied to verdana but as you can see after I hit preview the first word is obviously a different font.  When I go back to edit and put the cursor in that word it just says "Font Family"
![2016-05-04_18-27-10](https://cloud.githubusercontent.com/assets/8118574/15046898/ce1b0c5e-12a7-11e6-9a12-43c53b06c16f.png)

The other extremely challenging thing is the window you are editing in isn't the same size or even aspect ratio as the placeholder so what you edit looks different until you hit save and then preview.  This makes it especially challenging to try and make something scroll or to figure out spacing.

**Comment by donnapep** [comment]
@rjcahoy I'm having trouble reproducing this. Can you let me know what steps I can take to recreate? For example, are you typing in the text or pasting it? Are you selecting a font before entering text, or entering the text and then highlighting it and adjusting the font? Thx.

**Comment by alanclayton** [comment]
@rjcahoy Any feedback or steps we can follow to replicate?

**Comment by alanclayton** [comment]
@rjcahoy we're closing this issue. let us know if there are steps to replicate. As for your other point about the widget of the editor matching placeholder width, we have a card for that here https://trello.com/c/3fqwzgKJ/1593-text-editor-break-points-equal-to-width-of-placeholder
