### ISSUE TITLE
Can't get to all of text when editing in large placeholder

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/widget-text#103]
**How it works now:**
1. open this presentation: https://goo.gl/Gd5hbq.
2. edit major-text-1 placeholder.
3. click 'configure' on text widget and try to get to the text on the right side.
4.  The right half of the text is cut off and you can't get over there to edit it.

**How it should work:**
1. As you arrow over, the cursor should jump to the right and cause the text to scroll so you can see it.
2. There should be a horizontal scroll bar that lets you slide the text over to edit it.

**Comment by alanclayton** [comment]
Fix deployed.
