### ISSUE TITLE
WingDings font not rendering in editor on or display

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/widget-text#104]
**How it works now:**
1. Insert Text Widget into presentation
2. Type some text and set the font to WingDings
3. Preview or play the presentation on a display and the text remains text - not wingdings

**How it should work:**
You should see the WingDings font on preview and on the display

**Comment by stulees** [comment]
@raydurkin Did you notice this on a Windows machine when testing preview? Was it a Windows media player too? Thanks

**Comment by alanclayton** [comment]
WingDing fonts removed due to not being web safe.
