### ISSUE TITLE
When adding custom styling in the Text Widget, another font appears underneath the custom font

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-text#107]
**How to recreate**
Add the Text Widget, go to source and copy/paste the code below:

````
<ul style="list-style-image: url('http://walkinartcenter.org/ds/gallery/FA_WIAC-28x75-trans.png'); font-family: 'Abril Fatface', serif; font-size: 60px;">
<li>Weddings</li>
<li>Dinners</li>
<li>Receptions</li>
<li>Corporate Events</li>
<li>Training</li>
<li>Seminars</li>
<li>Trade Shows</li>
<li>Fund Raisers</li>
<li>Reunions</li>
</ul>
````

See this <a href="https://apps.risevision.com/editor/workspace/1dc60c78-438f-405b-8706-c97467aed4e0/?cid=960b72df-9af7-476b-8a47-b67ded4c779d">presentation</a>.

**What happens**

When I view the content in the Text Widget Editor and in the main Editor, I can see the custom font.  But when I preview, I can see an additional font underneath even though I cleared the formatting over the Text Widget.

**Notes**

A HTML Widget version of this does work but the user would like to know if they can style via the Text Widget.

https://community.risevision.com/rise_vision_inc/topics/css-in-text-widget-fonts-in-html-widget

**Comment by stulees** [comment]
@hcs0 Looking at the presentation you provided, I can see in HTML view that there is extra markup outside the placeholder, directly in the `<body>` of the HTML, see here - http://www.screencast.com/t/vYfQ2dQqF . This is resulting in the duplication of text showing. 

If you look at this presentation http://rva.risevision.com/#/PRESENTATION_MANAGE/id=3069ff93-1f43-4efb-8f0c-b7dc2c287419?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013 I created with Text Widget following your steps, there's no duplication and everything appears correctly. 

Given the above, there doesn't look to be a bug. Can you confirm and close? Thanks

**Comment by hcs0** [comment]
@stulees Thanks! Verified that this is not a bug/issue
