### ISSUE TITLE
Font Family Not Displaying Correctly in Preview

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-text#110]
I am specifying Roboto font in text widget.
http://www.screencast.com/t/8Xguvd2K

The font shows up correctly in the widget and in preview, but displays as Times Roman in Player in windows 10. http://www.screencast.com/t/GJPfhvv7lKT

Example Presentation (header-main placeholder): http://rva.risevision.com/#/PRESENTATION_MANAGE/id=b778771d-6572-4d39-85ac-6a7be80eedeb?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

Steps to Replicate:
1. Add text widget to presentation.
2. Copy and paste text into widget. (I copied from a power point slide but in source view of widget I dont see any code copied over that would cause the issue)
3. save presentation and view in player on windows 10 machine.

Note: ive seen this several time and it seems to be related to copying and pasting text from websites/pdfs/powerpoint ect. I can resolve by typing by hand or clearing formatting completely and starting over but I think this is common practice for people to copy/paste.

**Comment by rodrigopavezi** [comment]
I troubleshooted this issue and I found out that for some reason the editor did not behaviour as normal when you pasted the text. When looking at the html of the text on the editor it should had added font sans-serif as fallback like below

`font-family: Roboto, sans-serif;`

The missing font fallback causes the settings to not consider the google font. We could try to find a fix for that but I could not replicate the same so I believe we can go with a workaround in which you can use the clean format tool from the editor. That will remove any windows powerpoint font settings allowing you to select the Roboto one from the editor. I tried that with the presentation in this case and it worked.

Cheers
