### ISSUE TITLE
Text font changes itself only on first word of a sentence after changing whole sentence text size.

### ISSUE THREAD

**Issue by joelasso** [Rise-Vision/widget-text#112]
**How to recreate**

1. Placeholder --> Text Button Text Settings window comes up (Verdana 24px shows as default) 
2 . Enter Text Ex. "This is a test..." 
3. Click Save (Things seem fine) 
4. On left pane, click Text Widget again to edit the text 
5. Click in text again, then do Ctrl+A to select all 
6. Change font size to 72px 
7. Click Save

**What Happens**
First word of text will change to Times New Roman

**What should happen**
First word remains unchanged

I created this presentation for the text and you can see the first word changed there:

https://apps.risevision.com/editor/workspace/5f7065f3-0881-467c-908a-a79185046dd0/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Comment by joelasso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 112 - Text font changes on first word after changing text size](https://trello.com/c/p4k24Ysx/3246-issue-112-text-font-changes-on-first-word-after-changing-text-size)

**Comment by alanclayton** [comment]
Correction has been released.
