### ISSUE TITLE
Text stuck on Verdana font

### ISSUE THREAD

**Issue by joelasso** [Rise-Vision/widget-text#114]
How to recreate

Add Placeholder > Text Button>Text Settings window comes up (Verdana 24px shows as default)
Enter Text.
Click Save.
On left pane, click Text Widget again to edit the text
Click in text again, then do Ctrl+A to select all
Change font type to any other font for example Impact
Text will not change font

What should happen
Font on the text should change

I created this presentation to recreate the issue:
https://apps.risevision.com/editor/workspace/5f7065f3-0881-467c-908a-a79185046dd0/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

This is the presentation from the user that reported the issue: 
https://apps.risevision.com/editor/workspace/0664916b-5ef7-4232-860b-e584e1f474e7/?cid=5c02740b-682f-4daf-8490-2d14c5f28952

**Comment by joelasso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Text stuck on Verdana font #114](https://trello.com/c/VHQjNUst/3413-1-text-stuck-on-verdana-font-114)

**Comment by rodrigopavezi** [comment]
https://github.com/Rise-Vision/widget-text/pull/115
