### ISSUE TITLE
Emoji doesn't match on Preview vs Display

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/widget-text#123]
**How To Recreate**
1. Create a Text item in Placeholder
2. Copy and paste some emoticons that will fill the Text container
3. Preview content and ensure visibility of icons
4. Publish same content to a Display and observe cut-off of same icons

**What Happens**

On Preview:
![image](https://user-images.githubusercontent.com/11826611/41243856-598d86e2-6d71-11e8-9b2e-db02dba4368a.png)
On a Display:
![image](https://user-images.githubusercontent.com/11826611/41244006-ca837078-6d71-11e8-9329-dec49e07f111.png)

**What Should Happen**
Icons should match exactly on both Preview and Display

**Comment by sheadarlison** [comment]
@RV-Adrian what operating system is your display?

**Comment by RV-Adrian** [comment]
@sheadarlison I saw this on two Displays, both Win10 (one NUC and one Intel Compute Stick)

**Comment by sheadarlison** [comment]
@RV-Adrian the emojii looking different in preview vs display is because different operating systems render emojiis differently (https://emojipedia.org/heavy-black-heart/). I'm not sure why it was getting cut off though, could you either provide a link to the Presentation or paste the code that contains the placeholder and widget here?  See example: 

![screen shot 2018-06-19 at 12 51 39 pm](https://user-images.githubusercontent.com/9273546/41612010-9c374e0c-73bf-11e8-9657-fe3f44d349f5.png)

**Comment by RV-Adrian** [comment]
@sheadarlison 
I'll try that today!

**Comment by sheadarlison** [comment]
Sorry @RV-Adrian, I'm not sure I follow, what are you trying today?

**Comment by RV-Adrian** [comment]
@sheadarlison Try to get the code you need for reference. To clarify, I deleted the Company that originally had this Presentation to test out some Plan stuff. Looks like I'll have to recreate on my side.

**Comment by sheadarlison** [comment]
Ah thanks! @RV-Adrian

**Comment by sheadarlison** [comment]
@RV-Adrian did you have any luck recreating this?

**Comment by RV-Adrian** [comment]
I set up a new Company and Presentation here.
https://apps.risevision.com/editor/workspace/c3915515-e888-4996-a5c3-2e673e700a20/?cid=7b0128fb-08b9-4ef4-8252-43669a467668

The emoji look okay there and in the Preview, but on Display it appears like this:
![issue](https://user-images.githubusercontent.com/11826611/41860457-be238d9e-786c-11e8-8546-7056a89bbc4d.jpg)

Given your findings on the system-driven emoji, it's likely that the kerning is different with the various system fonts and our containers/placeholders can't necessarily accommodate for that?  If so, I'd guess the only workaround would be to change how Viewer handles emoji rendering. 
Let me know if you need any more specific info 👍

**Comment by sheadarlison** [comment]
@RV-Adrian Yeah I think the different kerning is the issue. I think this is a limitation of our widgets/viewer and it doesn't make sense for us to change the behaviour of them. 

I'm going to close this, let me know if you have questions. 

Thanks
