### ISSUE TITLE
The spell check built into the browser doesn't work in the Text Widget

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-text#144]
1. Add a text widget 
2. make a typo 
3. no red underline appears to correct it 

What should happen: The browser sees the problem, underlines it red, and a user can correct. 

Spell check does seem to work in the text component.

**This was reported by a user**

**Comment by olegrise** [comment]
Fixed

**Comment by sheadarlison** [comment]
Thank you @olegrise!
