### ISSUE TITLE
Text Sizes

### ISSUE THREAD

**Issue by cincydonuts** [Rise-Vision/widget-text#151]
96 px worked great for 1080p displays. Unfortunately, they're becoming scarce as the display market pushes higher and higher resolutions 4k and beyond. Even on a 4k display, 96 px is incredibly small. The text widget should either include much larger sizes, allow the use of arbitrary size input, or both. I've submitted the same to Rise Vision.

I have tried to use the HMTL view of the presentation designer to set larger text sizes, but that only results in the text size becoming 14 px.

**Comment by alanclayton** [comment]
@cincydonuts my recommendation would be to use one of our pre designed templates which support a max size of 200px and scales according to screen resolution. You can find the predesigned templates by doing the following: 

1. Sign into your account and navigate to [Presentations](https://apps.risevision.com/editor/list)
2. Select "Add From Template" 
3. All the templates shown, excluding the one called "Blank Landscape" will be have as described above. 

Let me know if that would be an option for you. If not, you can define a custom font for the text widget using the "source code" option on the widget settings page per the screenshot below. 

![image](https://user-images.githubusercontent.com/6854911/113757399-2dc63980-96d8-11eb-9778-35c43f489444.png)

**Comment by stulees** [comment]
Solutions were provided to user, closing defect.
