### ISSUE TITLE
Pasting text and clicking save does not save text

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/widget-text#155]
### What is the expected behavior from the user’s point of view? 
I can paste text into the text widget and click save to easily add text to the widget.

### What is the actual behavior from the user’s point of view? 
Pasting text into the text widget adds it correctly, but clicking "Save" does not save it.

### What steps can be taken to reproduce the actual behavior?
1. Create a presentation from the blank template
2. Add a placeholder
3. Add the text widget
4. Paste text into the widget
5. Click save

You can work around this by making another manual edit after pasting the text.  i.e. paste the text in and then add a character.  Clicking save will retain all the text.

**Comment by olegrise** [comment]
Issue is fixed.
