### ISSUE TITLE
Text Widget not being able to scroll left, will only scroll up.

### ISSUE THREAD

**Issue by cameronreidrisevision** [Rise-Vision/widget-text#160]
### What is the expected behavior from the user’s point of view? 
Text Widget should scroll to the left if that is the option set.

### What is the actual behavior from the user’s point of view? 
Text Widget will only scroll up regardless if the left is selected. 

### What steps can be taken to reproduce the actual behavior?
Create a blank template, add the Text Widget, and set it to left.

**Comment by stulees** [comment]
@cameronreidrisevision Can you provide (on Slack) a link to a presentation that is exhibiting the problem? Thanks
