### ISSUE TITLE
Text Widget font 

### ISSUE THREAD

**Issue by justinsmith1** [Rise-Vision/widget-text#43]
When you add a new Text Widget, it appears to the user that it defaults to Arial 14pt:
screenshot: http://screencast.com/t/lVIyIgMM

However, once you save the Widget settings, and publish the presentation, the font that is shown is not Arial 14pt:
screenshot: http://screencast.com/t/Zp7ziCpIhMa

You have to go back to the Widget settings, highlight your text, then select Arial from the dropdown menu, save the Widget settings, and re-publish the presentation.
screenshot: http://screencast.com/t/fAXiNrPmAq

At that point, the text displayed in the presentation from the Text Widget is correct (Arial 14pt):
screenshot: http://screencast.com/t/XnBAx3MU

**Comment by mmeiers** [comment]
Here is a presentation where you can see the problem
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=0200230a-3038-4a94-b586-59601d3e1b0e?cid=cb9c50b7-193c-4ada-bd72-f25b2202777c

Font is configured as Arial but shows as Times Roman

**Comment by ashleighalmeida** [comment]
How it works now:

User adds Text Widget.
User sets font to "Avant Garde"
User hits "Save".
In the editor, and preview, font appears to be in Times New Roman or Georgia.
User opens Text Widget configuration again to retry.
Font is set to "Arial" in the dropdown, and the font preview field is set to "Avante Garde"
User hits "Save" again.
In the editor viewer and preview the font will appear to be in "Times New Roman".

How it should work:

User adds Text Widget.
User sets font to "Avante Garde"
User hits "Save"
In the editor, and preview, font appears to be in "Avante Garde" as configured.

List of fonts that causes this issue:

Century Gothic
Avant Garde
Book Antiqua
Calibri
Candara
Consolas
Fank Gothic Medium
Lucida Sans Typewriter

All of the other fonts will display as configured.

Demo: https://drive.google.com/a/risevision.com/file/d/0B5_6TQ6T_mw1bDBmclJMa0Zvemc/view?usp=sharing

https://trello.com/c/tDLvLTGD/1145-3-font-issue-with-new-editor

**Comment by btfrise** [comment]
To clarify, this is an issue with the Text Widget and happens in both Editor and Classic Editor.

**Comment by donnapep** [comment]
Fixed in version 1.0.0 of Widget.
