### ISSUE TITLE
Widget Text Stage Size

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-text#46]
When you edit/configure the widget the stage size for inputing text is relative to the size of the browser. 
It would better if the stage size represented the size of the placeholder.

That way you will have preview or idea where lines are going to break.

video overview: 
http://www.screencast.com/t/gjCnra5Hk

FYI @alanclayton

**Comment by donnapep** [comment]
@alanclayton @mmeiers I don't think this is going to be possible without changes to the editor. The Widget doesn't know the dimensions of the Placeholder that it's in from the Settings page. This information is only accessible in the Viewer.

**Comment by alanclayton** [comment]
@donnapep Thanks! @mmeiers Given the above I don't think we need to worry about this and will close this. Let me know if you disagree. Thanks

**Comment by mmeiers** [comment]
@alanclayton @donnapep fine with me
