### ISSUE TITLE
Text Highlighting

### ISSUE THREAD

**Issue by dlugo00** [Rise-Vision/widget-text#48]
With the new Text Widget, users can highlight text by selecting the text and dragging it (http://www.screencast.com/t/L3OA4lyG5Wd).

**Comment by alanclayton** [comment]
@mmeiers is this still an issue?

**Comment by mmeiers** [comment]
@alanclayton At a quick glance Im not able to get the text widget to work at all. Im going to look into this more after lunch.

**Comment by mmeiers** [comment]
@alanclayton Yep looks like its an issue still. With text item we could add css to the a presentation html and it would disable highlighting. https://css-tricks.com/almanac/properties/u/user-select/

However this doesnt work with text widget. I believe @donnapep mentioned at one time this would be something that would have to change in the widget code to work.

**Comment by donnapep** [comment]
Fixed in latest version of Text Widget.
