### ISSUE TITLE
Custom Font URL not preserved in Widget Settings

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-text#51]
If you configure the Text Widget to use a custom font, the URL you specified doesn't appear on a subsequent edit. 

Presentation, https://goo.gl/FH8gR5

Open the Text Widget from the Placeholder "Product". Notice the font selected is "Custom Font". If you open up Custom Font dialog the URL is empty. http://www.screencast.com/t/WdGSZ7LtMwq.

**Comment by donnapep** [comment]
@alanclayton Can you confirm that this Presentation should open with the new Editor?

Also, none of the Text Widgets in the Product placeholder are showing as "Custom Font". I am seeing Arial selected for each one. Can you clarify? Thx.

**Comment by donnapep** [comment]
@alanclayton Ah, looks like I actually need to click on text that is using a custom font.

**Comment by donnapep** [comment]
Fixed by #52

**Comment by donnapep** [comment]
This is an issue again in version 1.0.0 of the Widget. To add to it, when placing your cursor over text that uses a custom font and selecting "Use Custom Font" from the dropdown, the font family of the text changes.

**Comment by alanclayton** [comment]
@donnapep Once a custom font is added it is preserved in the font list dropdown menu. I think we can improve that work flow to make it more intuitive, but I don't think we have an issue of custom fonts not being preserved. If you agree, I think we can close this one.

**Comment by donnapep** [comment]
@alanclayton Sounds good.
