### ISSUE TITLE
Font Size wont Change for Copy/ Pasted Text

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-text#53]
Steps to replicate:
Copy and Paste text from a webpage into tex widget. 
example: http://lj.libraryjournal.com/

Try and change the fonts size.
You will notice you cant do so.

Video Overview: http://www.screencast.com/t/DDwsk82uQgp

**Comment by mmeiers** [comment]
further testing: http://www.screencast.com/t/TiCv5Hko

**Comment by donnapep** [comment]
@mmeiers The new Text Widget has a source code option now that can be used to clean up the HTML. Is that an acceptable solution to this issue of copying and pasting text?

**Comment by mmeiers** [comment]
@donnapep I think this can be closed. I havent noticed this with the new one and i think the clear formatting button would take care of it also.

**Comment by donnapep** [comment]
@mmeiers OK, thx.
