### ISSUE TITLE
'More Fonts...' selection showing incorrectly in main font list 

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/widget-text#54]
*Issue*

After making a selection from the 'More Fonts...' list the same selected font name will display in the main dropdown list of fonts, however it will be formatted as a basic serif font (possible Times New Roman).

*Steps to Recreate*

1. Select a font using the 'More Fonts...' option, e.g. Lato. 
2. Use the font in the widget
3. Return to the main font menu and name of the font will have been added to the list, formatted with a serif font. Selecting the font using this name will result in a serif font being applied to the text.

**Comment by donnapep** [comment]
Closing as there is no longer a "More Fonts..." option. Google fonts are listed directly in the font dropdown.
