### ISSUE TITLE
Font reads as Arial 14pt by default (possibly linked to issue #43)

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/widget-text#55]
After saving text as a font and font size other than Arial and 14pt, when you reopen the text widget it will tell you that the text is Arial 14pt. Particularly problematic if you are using white text as it looks as though the widget is empty.

**Steps to Recreate**

1. Open the text widget and type some text. Set the text to be anything other than Arial 14pt (e.g. Avant Garde 36pt) using the dropdown menus.
2. Save these settings and exit the widget.
3. Reopen the widget and the settings will show Arial 14pt while the text will actually be different. Placing the cursor in the text will produce the correct font readings.

**Comment by donnapep** [comment]
This is still occurring, but I'm not sure it's worth fixing as the cursor is technically outside of the text that has the styling applied to it when the editor first loads, and clicking inside the text updates the dropdowns correctly. @alanclayton FYI.

**Comment by alanclayton** [comment]
@donnapep Agreed this doesn't need to be addressed and expectation is that previously applied values will be reflected when focus is put on editor. Closing issue.
