### ISSUE TITLE
Underline does not change color when highlighted text color is changed.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-text#56]
Steps to reproduce:
1. Add a Text Widget to a placeholder
2. Select underline and type in some text
3. Highlight that text and change the color

Result:
The letters of the text change, but the underline color does not change. This persists through preview and is not only showing up on the Editor.

How it should work:
When text that is underlined is highlighted and the color is changed, the underline should also change color.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=d0609664-c33f-4d32-a68b-8d2864194d6c

OS:
OS X

Chrome Ver:
46.x

**Comment by donnapep** [comment]
No longer an issue.
