### ISSUE TITLE
Fonts above 30px overlap top of line.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-text#57]
Steps to reproduce:
1. Add text widget to a placeholder
2. Select a font at 30px or above
3. Add text content

Result:
If this is on the first line of the text box, the text will be cut off at the top. If it is on a following line, it will cut off the line above it.

How it should work:
Each font size should fit within it's own line.

Screenshot:
http://www.screencast.com/t/xQ1UdSMJ2D

OS:
OS X

Chrome Ver:
46.x

**Comment by donnapep** [comment]
No longer an issue.
