### ISSUE TITLE
When using a custom font, text does not completely scroll.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-text#58]
Steps to reproduce
1. Create a placeholder with the Text Widget
2. Set scroll to continuously
3. Select a custom font
4. Add enough text to scroll

What I expect to happen
The entire contents of the text box should scroll through the placeholder.

What actually happens
The text scrolls, and stops in the middle of a portion of the text.

Presentation:
https://storage.googleapis.com/risemedialibrary-003fe743-0982-4473-9111-738c28b52055/Fonts/EraserRegular.ttf

Chrome 47.*
OSX

**Comment by btfrise** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/btf@risevision.com/conversations/1519921176

**Comment by alanclayton** [comment]
@btfrise This doesn't appear to be an issue with the latest version of Text Widget available from the Store. We are going to close this. Let us know if you think otherwise. Thanks
