### ISSUE TITLE
Custom font does not work if there is spaces in the TTF

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-text#59]
**How to duplicate**
Create a Text Widget
Use the font https://storage.googleapis.com/risemedialibrary-960b72df-9af7-476b-8a47-b67ded4c779d/It%20never%20stops%20and%20we'll%20never%20learn.ttf
Save and preview you will notice the custom font does not appear.

If you use https://storage.googleapis.com/risemedialibrary-960b72df-9af7-476b-8a47-b67ded4c779d/Itneverstopsandwellneverlearn.ttf the custom font appears both in preview and Display.

**Env**
Chr 47

**Comment by donnapep** [comment]
This is still an issue in version 1.0.0 of the Widget.

**Comment by stulees** [comment]
This has been fixed by #80 , closing. FYI @hcs0
