### ISSUE TITLE
Fonts not displaying as configured (RVA + New Editor)

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/widget-text#60]
<b>How it works now:</b>

User adds Text Widget.
User sets font to "Avant Garde"
User hits "Save".
In the editor, and preview, font appears to be in Times New Roman or Georgia.
User opens Text Widget configuration again to retry.
Font is set to "Arial" in the dropdown, and the font preview field is set to "Avante Garde"
User hits "Save" again.
In the editor viewer and preview the font will appear to be in "Times New Roman".

<b>How it should work:</b>

User adds Text Widget.
User sets font to "Avante Garde"
User hits "Save"
In the editor, and preview, font appears to be in "Avante Garde" as configured.

List of fonts that causes this issue:

Century Gothic
Avant Garde
Book Antiqua
Calibri
Candara
Consolas
Fank Gothic Medium
Lucida Sans Typewriter

All of the other fonts will display as configured.

<b>Demo:</b> https://drive.google.com/a/risevision.com/file/d/0B5_6TQ6T_mw1bDBmclJMa0Zvemc/view?usp=sharing

https://trello.com/c/tDLvLTGD/1145-3-font-issue-with-new-editor

**Comment by mmeiers** [comment]
@ashleighalmeida Fyi this may be related to issue
#55 and #43.

I think you have a good description here though. I might suggest reviewing them and if you feel they are the same just add to the comments of 43 and delete this one. If you think they are different feel free to leave open.

**Comment by ashleighalmeida** [comment]
@mmeiers #43 seems the most related, I will leave a comment there.
