### ISSUE TITLE
First word does not preserve formatting

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/widget-text#73]
**How to duplicate**

- Add a Text Widget and add a few words.
- Highlight the text and apply a font of Courier New.
- Save Widget settings.
- Open Widget settings.
- Notice that the first word is styled differently than the rest of the text.

**Env**
Chr 48

**Comment by alanclayton** [comment]
@donnapep can this be closed now?

**Comment by donnapep** [comment]
@alanclayton Yup.
