### ISSUE TITLE
Highlighting text and applying a custom font does not work

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/widget-text#74]
**How to duplicate**

- Add a Text Widget and add a few words.
- Highlight the text and apply this custom font to it - https://storage.googleapis.com/risemedialibrary-960b72df-9af7-476b-8a47-b67ded4c779d/Itneverstopsandwellneverlearn.ttf
- Note that the highlighted text does not update to show the custom font.
- Continue typing additional text.
- Note that the new text has the custom font applied to it. 

**Env**
Chr 48

**Comment by alanclayton** [comment]
@donnapep can this be closed now?
