### ISSUE TITLE
Font styles lost when text is highlighted and "Load More Fonts..." is selected

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-text#88]
Add text to the Text Widget editor and apply any font style. Then highlight the text and select "Load More Fonts..." from the font family drop down menu. When you do this, the font style previously applies is lost and now shows the selected font as "Load More Fonts...".

"Load More Fonts..." should never show as a valid font type and previously applied font families should be preserved in the scenario described above.

**Comment by donnapep** [comment]
Closing as "Load More Fonts..." is being removed.
