### ISSUE TITLE
Indentation not preserved in widget editor for single line of text

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/widget-text#93]
## How it works now:
1. Add a single line of text to in the editor and indent it to the right.
2. Save and preview the presentation and see the indentation in effect.
3. Reopen the text widget and the text no longer shows as indented, but in preview it still shows that it is.
4. Save and preview the presentation and the indentation is still in effect.

## How it should work:
If you have a single line of text, or a word, that is indented in the text editor, when you re-open the text editor you should still see that the text is indented to make alignment easier for users.

This only appears to be an issue with a single line of text. If you have more than one line the indentation is preserved in the editor and in the presentation. 

This is the Presentation used for testing:
https://apps.risevision.com/editor/workspace/c4ed851e-5ee5-4e6d-a45b-32f9890258ba/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Comment by stulees** [comment]
This has been fixed and deployed from PR #94 , closing. @pcsandford FYI
