### ISSUE TITLE
Text Widget in Editor Preview shows old text underneath new text

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-text#96]
Presentation:
https://apps.risevision.com/editor/workspace/64c374eb-39a3-474c-a26d-be70e9da7bd1/?cid=89ee55d6-79ee-4f76-a513-3ead77b236d3

Preview:
http://preview.risevision.com/?type=presentation&id=64c374eb-39a3-474c-a26d-be70e9da7bd1

The Placeholder showing the issue is spotlight-header

![text-widget-in-editor-preview-bug](https://cloud.githubusercontent.com/assets/9273546/13900516/0d596c98-ede7-11e5-85b6-51e900ecfba6.gif)

**Comment by alanclayton** [comment]
Not an issue. Overlapping text was bg image.
